services:
  client1:
    tty: true
    stdin_open: true 
    container_name: client1
    build: .
    privileged: true
    depends_on:
      - router
    networks:
      - network1
      - network2   
    command: sh -c "ip route delete default 
                    && ip rule add from 10.10.1.2 table 1
                    && ip rule add from 10.10.2.2 table 2
                    && ip route add 10.10.3.0/24 via 10.10.1.254 table 1
                    && ip route add 10.10.4.0/24 via 10.10.2.254 table 2
                    && ip mptcp limits set subflow 2 add_addr_accepted 2
                    && ip mptcp endpoint add 10.10.2.2 dev eth1 signal
                    && tail -f /dev/null"
    cap_add: 
      - NET_ADMIN
  client2:
    container_name: client2
    tty: true
    stdin_open: true 
    privileged: true
    build: .
    depends_on:
      - router
    networks:
      - network3
      - network4
    command: sh -c "ip route delete default
                    && ip rule add from 10.10.3.2 table 1
                    && ip rule add from 10.10.4.2 table 2
                    && ip route add 10.10.1.0/24 via 10.10.3.254 table 1
                    && ip route add 10.10.2.0/24 via 10.10.4.254 table 2
                    && ip mptcp limits set subflow 2 add_addr_accepted 2
                    && ip mptcp endpoint add 10.10.4.2 dev eth1 signal
                    && tail -f /dev/null" 
    cap_add: 
      - NET_ADMIN
  router:
    container_name: router
    build: .
    tty: true
    privileged: true
    networks:
      network1:
        ipv4_address: 10.10.1.254
      network2: 
        ipv4_address: 10.10.2.254
      network3: 
        ipv4_address: 10.10.3.254
      network4:
        ipv4_address: 10.10.4.254
    command: sh -c "ip route delete default 
                    && ip rule add from 10.10.1.2 table 1
                    && ip rule add from 10.10.2.2 table 2
                    && ip rule add from 10.10.3.2 table 3
                    && ip rule add from 10.10.4.2 table 4
                    && ip route add 10.10.3.0/24 via 10.10.3.2 table 1
                    && ip route add 10.10.4.0/24 via 10.10.4.2 table 2
                    && ip route add 10.10.1.0/24 via 10.10.1.2 table 3
                    && ip route add 10.10.2.0/24 via 10.10.2.2 table 4
                    && tail -f /dev/null"
    cap_add: 
      - NET_ADMIN

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.1.0/24"
  network2:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.2.0/24"
  network3:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.3.0/24"
  network4:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.4.0/24"
